### ISSUE TITLE
Suggestion: Comparison to Similar Libraries

### ISSUE THREAD

**Issue by cocowalla** [agileobjects/AgileMapper#1]
It might be helpful to add a comparison with similar libraries, such as AutoMapper and ValueInjecter, to the readme and/or wiki. If not a direct comparison, then perhaps something basic as to why someone might want to choose AgileMapper over the alternatives.

**Comment by SteveWilkes** [comment]
Thanks for the suggestion! I'll definitely draw up a comparison grid - I've added it to the [v1 Tasks](/agileobjects/AgileMapper/projects/1) project.
