### ISSUE TITLE
Dissabling Entity Mapping rules

### ISSUE THREAD

**Issue by YandyZaldivar** [agileobjects/AgileMapper#102]
Hi Steve, I need a global configuration option to disable Entity Mapping rules and get all my Key Id fields effectively mapped. While reviewing some of my projects in details I found that the default behavior will broke 90% of mappings, and won't add practical value in any of the rest 10%.

**Comment by SteveWilkes** [comment]
Hi!

Thanks again for the feedback! I'm wondering if I should add a global disable setting, or just change the default behaviour. I'll revisit the reasons I made it behave the way it does and get back to you.

Cheers,

Steve

**Comment by YandyZaldivar** [comment]
To be honest, I prefer if you change the default behavior. Thinking in basic CRUD operations: delete, update and read all need a key, and for create when the key is autogenerated it is a must for the client to send no key or a key with the default value, otherwise the operation should fail. For nullable values I am also not sure if there is a good point.

In most projects I have entities with composite keys and I use to decorate them with the key attribute even when they are setup using the fluent API. Agile.Mapper gets even more painfull to use for these cases.

**Comment by SteveWilkes** [comment]
I think there's something I'm missing - the use cases you mention - "delete, update and read all need a key, and for create when the key is autogenerated it is a must for the client to send no key or a key with the default value" were the motivation behind the mapper's entity key behaviour. [Keys aren't mapped](https://github.com/agileobjects/AgileMapper/wiki/Entity-Mapping) because existing entities will already have one, and new entities - to be written to a table with an auto-incrementing primary key - shouldn't have one.

What is the behaviour you'd like to change?

**Comment by YandyZaldivar** [comment]
I was updating an existing project from AutoMapper to AgileMapper and after upgrade 90% of mappings were wrong due to AgileMapper not mapping keys, for example:

```
        public async Task TemplateLock(TemplateApiModel apiModel)
        {
            var template = AutoMapper.Map<TemplateApiModel, Template>(apiModel);
            //var template = AgileMapper.Map(apiModel).ToANew<Template>();

            var entity = DatadinDbContext.Attach(template);
            entity.Property(p => p.Locked).IsModified = true;

            foreach (var key in Cache.Keys)
                if (key.Model == apiModel.ModelId && key.Year == apiModel.Year &&
                    (key.Month == apiModel.Month || key.Month == null) &&
                    (key.Day == apiModel.Day || key.Day == null))
                    Cache.TryRemove(key, out var value);

            await DatadinDbContext.SaveChangesAsync().ConfigureAwait(false);
        }
```
This code fails when using AgileMapper because the Template key is not mapped. Here I am using an Update operation but the same goes for Delete `DatadinDbContext.Templates.Remove(template);` if the Template key is not mapped from the DTO the delete operation will fail. Now, in a Create operation the client when sending a DTO should set the Key equal to is default value or omit it if the model have an auto-increment primary key or set it to the desired value if the primary key is not auto-generated, for that reason it makes more sense to always map the key. For all other cases, at least in my projects (these are my particular needs which doesn't need to be generalized), I also prefer that the key(s) always be mapped without having to resort to complicated constructions like:
```
            modelBuilder.Entity<Group>().HasData(GroupApiModel.GeiaGroups.Select(p =>
                mapper.Map(p).ToANew<Group>(q => q.Map(s => s.Source.Id).To(t => t.Id)
                    .And.Map(s => s.Source.DivisionId).To(t => t.DivisionId))).ToArray());
```

> What is the behaviour you'd like to change?

My request whether the default behavior of no mapping keys remain or not, is to have a global configuration option to disable entity mapping rules.

PS: Due to the complexity of maintaining object mappings, choosing the right library for the task and other details, I am getting to the conclusion for future work that the best solution is not having DTOs, but to expose database models directly whenever possible.

**Comment by SteveWilkes** [comment]
Ok, thank you - I understand the problem now. I think to cover all scenarios I'll add a global config option to always map keys, and add mapping-scoped options to turn key mapping on or off. Thanks for taking the time to clarify :)

**Comment by SteveWilkes** [comment]
This is supported in the latest code - release to follow! Configured using:

```C#
// Map entity keys by default:
Mapper.WhenMapping.MapEntityKeys();

// ...then ignore entity keys for a specific mapping:
Mapper.Map(sourceDto).ToANew<MyEntity>(c => c.IgnoreEntityKeys());
```

Thanks again for the feedback :)

**Comment by YandyZaldivar** [comment]
Excellent.

So, if I don't call `Mapper.WhenMapping.MapEntityKeys();` then I can assume this `Mapper.Map(sourceDto).ToANew<MyEntity>();` will map my entity keys?

**Comment by SteveWilkes** [comment]
This is now supported in [the v1 package](https://www.nuget.org/packages/AgileObjects.AgileMapper) on NuGet - I'll be updating the documentation tomorrow.

Cheers!

Steve

**Comment by YandyZaldivar** [comment]
Congratulations for the v1 achievement :)

**Comment by SteveWilkes** [comment]
Thanks! It's been a long time coming :)
