### ISSUE TITLE
Composite key in IdentifyUsing

### ISSUE THREAD

**Issue by rafalkasa** [agileobjects/AgileMapper#104]
Please let me know if it is possible to use the composite key in I`dentifyUsing<TId>(Expression<Func<TObject, TId>> idExpression)`?
Maybe you exactly resolved a quite similar scenario?

 ```
mapper.WhenMapping
                        .InstancesOf<Person>()
                        .IdentifyUsing(p => p.PersonId, p.PersonTypeId));
```

**Comment by SteveWilkes** [comment]
Hi!

I think something like this should work:

```C#
mapper.WhenMapping
    .InstancesOf<Person>()
    .IdentifyUsing(p => p.PersonId + "_" + p.PersonTypeId));
```

Let me know how you get on!

Cheers,

Steve

**Comment by rafalkasa** [comment]
This is kind of magic for me but it's working! 
@SteveWilkes thank you

**Comment by SteveWilkes** [comment]
Great! :)
