### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by vsederburg** [agileobjects/AgileMapper#120]
Hi again, I seem to have another dto that it doesn't like.

Expression of type 'System.Collections.ObjectModel.Collection`1[mt.Shared.DTOs.Settings.AddressDateRangeDto]' cannot be used for assignment to type 'System.ComponentModel.BindingList`1[mt.Shared.DTOs.Settings.AddressDateRangeDto]'

I don't understand why it thinks it's a collection being assigned to a BindingList. I'm making a DeepClone of an AddressDto that has a property that is a BindingList<AddressDateRangeDto>. Since it's cloning itself, it should be bindinglist to bindinglist, shouldn't it?

**Comment by vsederburg** [comment]
Oh, running the latest version 1.2.0

**Comment by vsederburg** [comment]
Oops, didn't mean to close this.  Meant to just say I'm running the current version 1.2.0

**Comment by SteveWilkes** [comment]
Hello!

This turned out to be an issue mapping types derived from `Collection<T>` - I've fixed it and published a v1.3 preview [to NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper/1.3.0-preview).

Thanks for the bug report! :)

Steve

**Comment by vsederburg** [comment]
Thanks for the fast response. I’ll give it a go later today and confirm.  

Thanks again!
Van

**Comment by SteveWilkes** [comment]
This is fixed in v1.3, now available [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper/).

Cheers! :)
