### ISSUE TITLE
DDD usecase

### ISSUE THREAD

**Issue by baoduy** [agileobjects/AgileMapper#122]
Just found this library and it shall be potentially replaced AutoMapper. However, I’m looking for a DDD mapping use case which using parameters constructor when creating and a method for updating. Please share your experience 

Thanks
Duy

**Comment by bslbckr** [comment]
Hi, I'm not sure, if I understood your question correctly, but are you trying to do something along these lines: https://dotnetfiddle.net/VzO9rp

**Comment by baoduy** [comment]
@bslbckr Yes, I'm looking for something like that, let's me try to see it works for my case or not.

**Comment by SteveWilkes** [comment]
Hi Duy,

Sorry for the delay in replying - and thanks to @bslbckr! Just to note, the example's constructor parameter configuration isn't necessary - the source and target names match, so the mapper will pair them up for you :)

AgileMapper should be good fit for DDD mapping use cases:

 - [Constructor parameters](https://agilemapper.readthedocs.io/Object-Construction) are automatically matched from source members
 - Existing complex types and [collections](https://agilemapper.readthedocs.io/Collections) are reused - handy if you're mapping to an object tracked by an ORM
- Entity Keys are [treated appropriately](https://agilemapper.readthedocs.io/Entity-Mapping)
- [Mapping plans](https://agilemapper.readthedocs.io/Using-Execution-Plans) are easy to see, and optionally [validate](https://agilemapper.readthedocs.io/Validating-Mappings) mapping completeness and [enum mapping](https://agilemapper.readthedocs.io/Enum-Mapping) - enum validation can be very useful when mapping objects across domain boundaries
- Entity Framework 5 -> Core queries [can be enhanced](https://agilemapper.readthedocs.io/query-projection/Entity-Framework), to support projections to DTOs with data type conversions where necessary

Hope that helps, and do let me know if you've other questions or you find any issues!

Cheers,

Steve
