### ISSUE TITLE
[Help Request] Mapper fails to create instances

### ISSUE THREAD

**Issue by bslbckr** [agileobjects/AgileMapper#129]
Dear @SteveWilkes , I once again have a mapping problem, briefly shown in this fiddle: https://dotnetfiddle.net/6ufGhK 

I'm using the new `ToTarget<>()` Method to specify the target. However, the target-classes do not offer a parameter-less constructor and hence I specify a more detailed mapping for the concrete case, where I give a constructor-parameter using `ToCtor<>()`. 

At the moment I'm not quite sure, whether or not the mistake is at my site. Could please have a quick look?

**Comment by SteveWilkes** [comment]
Hello again! The constructor parameter configurations will need to come before the `ToTarget<>()` configurations so that mapper knows how to map the target types, but unfortunately even with that changed it is missing that it should know how to construct them, and throwing an exception.

I'll take a look and sort it out!

**Comment by bslbckr** [comment]
Unfortunately, the observed behavior does not change, even if I give an explicit factory-method for instance creation. I.E. `WhenMapping.From<Source.SituationObject>().To<Target.SituationObject>().CreatesInstancesUsing(...)`

**Comment by SteveWilkes** [comment]
Yeah - it's nothing you're doing wrong - `ToTarget` includes a check that the configured type can be constructed, but it's not taking types with configured constructions into account correctly. I'll have it sorted out soon! :)

**Comment by SteveWilkes** [comment]
This is fixed as of v1.4-preview2, which is available [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper). I'd make a fiddle, but dotnetfiddle doesn't seem to be working for me at the moment...

Let me know how you get on! Thanks again for the feedback!

**Comment by bslbckr** [comment]
Thanks for the fix, at first sight it looks good.

**Comment by SteveWilkes** [comment]
v1.4 is now [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper). Cheers! :)
