### ISSUE TITLE
[Help Request] How to use createInstancesOf<>

### ISSUE THREAD

**Issue by bslbckr** [agileobjects/AgileMapper#135]
I noticed a difference between my expected and AgileMapper's acutal behavior when it comes to mapping to interfaces. 
Let's start with the MWE:
```
namespace Source {
  public class Data { public string Name {get; set;} }
}
namespace Target {
  public interface IData { string Name {get; } }
  public class Data : IData {
    public string Name {get; set;}
  }
}

Mapper.WhenMapping.To<Target.IData>().CreateInstancesOf<Target.Data>();
```

My expectation is that the mapper-configuration tells AgileMapper to create an instance of `Target.Data` whenever an instance of `Target.IData` is required. Hence, a mapping from `Source.Data` to `Target.IData` should be possible and yield an instance of `Target.Data`. 
However, the observerd behavior is that AgileMapper returns `null` as it cannot create instances of `Target.IData`. 

Is this behavior correct and required and if so, what are the reasons behind? 

I also tried to find a way around using `ToTarget<Test.Data>()` but failed. I was able to find a rather dirty hack using: `WhenMapping.From<Source.Data>().To<Target.IData>().If(d => true).MapTo<Target.Data>()`

**Comment by SteveWilkes** [comment]
Hello!

`CreateInstancesOf<T>` is intended to be a intermediate step to configuring how the mapper should create instances of _members_ of type `T` when mapping from the specified type, so in the case of:

```C#
Mapper.WhenMapping
    .To<Target.IData>()
    .CreateInstancesOf<Target.Data>();
```

...it would be expected to supply a factory method telling the mapper how to create instances of `Target.Data` when mapping to a `Target.IData` instance, like this:

```C#
Mapper.WhenMapping
    .To<Target.IData>()
    .CreateInstancesOf<Target.Data>()
    .Using(ctx => new Target.Data { Name = "Created!" });
```

You can tell the mapper how to create a `Target.IData` instance using:

```C#
Mapper.WhenMapping
    .To<Target.IData>()
    .CreateInstancesUsing(ctx => new Target.Data());
```

It should be noted that only mappable `Target.IData` members will then be mapped; as `Target.IData.Name` in your example is readonly, it wouldn't be populated. I've made [a fiddle](https://dotnetfiddle.net/Fsy74n) showing it in action.

Hope that makes sense + helps! :)

**Comment by bslbckr** [comment]
Yes, that's makes perfectly sense. Thank you.
Is there any way to detect such incomplete configurations and give a meaningful error-message?

**Comment by SteveWilkes** [comment]
There should be, yeah - I want it to be difficult to misuse the configuration. I'll add it to the list :)
