### ISSUE TITLE
Ability to ignore source fields

### ISSUE THREAD

**Issue by mikart143** [agileobjects/AgileMapper#137]
I am not able to find any config which could help with my problem. I want to update object but i don't want to update target fields with null fields from source. I want to ignore source fields if they are null.

**Comment by SteveWilkes** [comment]
Hi!

There's no quick way to achieve this, but it seems like a sensible thing to support, so I'll add it in. It's not going to be quick to add though, but thanks for the suggestion!

Cheers,

Steve

**Comment by SteveWilkes** [comment]
Implemention underway on [this branch](/agileobjects/AgileMapper/tree/features/SourceFiltering) :)

**Comment by SteveWilkes** [comment]
Well - I said it wouldn't be quick!

This is supported as of v1.5, which is now [on NuGet]|(https://www.nuget.org/packages/AgileObjects.AgileMapper). Sources can be ignored like this:

```cs
Mapper.WhenMapping
    .Over<Order>()                                   // Apply the filter to Order updates
    .IgnoreSources(c => c.If(string.IsNullOrEmpty)); // Ignore null or empty source strings
```

```cs
Mapper.WhenMapping
    .From<OrderDto>()             // Apply when mapping from OrderDto
    .Over<Order>()                // Apply the ignore to Order updates (optional)
    .IgnoreSource(dto => dto.Id); // Ignore the Order.Id property
```

...or like this:

```cs
// Source, target and mapping types are implicit from the mapping:
Mapper.Map(orderDto).Over(order, cfg => cfg
    .If((dto, o) => dto.Id == 0) // Apply the ignores if OrderDto.Id is 0
    .IgnoreSource(
        dto => dto.Id,               // Ignore Order.Id...
        dto => dto.OrderNumber);     // ...and Order.OrderNumber
```

...or like this:

```cs
Mapper.WhenMapping
    .IgnoreSourceMembersOfType<IDontMapMe>();
```

...and in [other ways](https://agilemapper.readthedocs.io/)!

Thanks again for the suggestion :)
