### ISSUE TITLE
Root Enum Pairing not working

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [agileobjects/AgileMapper#138]
I have tried using mapping 2 custom Enums but it always give default enum instead of mapping rules.

Code - ASP.Net Core 2.2
Agile library - AgileObjects.AgileMapper (1.3.0)

    public enum MyEnum
    {
        Hi,
        Hello
    }

    public enum MyEnumNew
    {
        NwmHello,
        NwmHi
    }

In my MappingConfiguration I have done

    public class MappingConfiguration : MapperConfiguration
    {
        protected override void Configure()
        {          
            Mapper.WhenMapping.PairEnum(MyEnum.Hi).With(MyEnumNew.NwmHi);
            Mapper.WhenMapping.PairEnum(MyEnum.Hello).With(MyEnumNew.NwmHello);            
        }
    }

and used it like 

    var myValue = Mapper.Map(MyEnum.Hi).ToANew<MyEnumNew>();

But it always gives `NwmHello`

**Comment by bslbckr** [comment]
I can confirm this behavior for version 1.4.0, too.

**Comment by SteveWilkes** [comment]
Hi!

Thanks for the feedback - I guess it was a lack of imagination on my part, but I never designed enum pairing to work with root enum values - it only works for enum members, [like this](https://dotnetfiddle.net/x9Jfup).

Makes sense that it should work, though - I'll sort it out!

Cheers,

Steve

**Comment by bslbckr** [comment]
In our use-case the problem occurred when using some fairy complex mappings, involving some factory-methods. Within the factory-mappings we would like to be able to reuse the currently configured enum-mapping.

**Comment by SteveWilkes** [comment]
This is supported in the latest code, release to follow. Thanks for the feedback! :)

**Comment by SteveWilkes** [comment]
This is supported as of v1.5-preview1, which I've just uploaded [to NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper). Thanks again! :)
