### ISSUE TITLE
*Id and *Identifier target properties are both mapped

### ISSUE THREAD

**Issue by GothikX** [agileobjects/AgileMapper#14]
Hi again :)

So I guess this isn't a big issue since I'm in control of the target types and renamed the properties, but I had both CustomId and CustomIdentifier properties on a type and when I tried to configure both of them it complained: `AgileObjects.AgileMapper.Configuration.MappingConfigurationException: 'Target.CustomIdentifier already has a configured data source'`

Just wondering if there's already a way to configure this or make it overwrite the mapping even if it exists. I guess it could be abused so I'm not sure I'd like it anyway.

**Comment by SteveWilkes** [comment]
Hey there! This is because a property named <blah>Id will be matched with <blah>Identifier, so the mapper thinks a data source has been set up for the latter when in fact it's only been set up for the former. Shouldn't be difficult to fix that - I'll check it out this week :)

**Comment by SteveWilkes** [comment]
This is fixed in the latest code - release to follow :)

**Comment by SteveWilkes** [comment]
This is now fixed in v0.11.
