### ISSUE TITLE
Entity Key mapping

### ISSUE THREAD

**Issue by muhammetsahin** [agileobjects/AgileMapper#143]
Hi,

I'm using v1.4.0

And i created extension like this:

`   public static class MapperExtensions
    {
        public static TSource Clone<TSource>(this TSource source)
        {
            return Mapper.DeepClone(source);
        }

        public static TDestination Map<TSource, TDestination>(this TSource source)
        {
            return Mapper.Map(source).ToANew<TDestination>();
        }

        public static TDestination Map<TDestination>(this object source)
        {
            return Mapper.Map(source).ToANew<TDestination>();
        }

        public static TDestination Map<TSource, TDestination>(this TSource source, TDestination destination)
        {
            return Mapper.Map(source).OnTo(destination);
        }

        public static IQueryable<TDestination> Project<TSource, TDestination>(this IQueryable<TSource> queryable)
        {
            return queryable.Project().To<TDestination>();
        }
    }`

 i want to convert domain model to view model and my model like this:

Model:

`public class Customer : Entity
    {
        public Customer(Guid id, string name, string email, DateTime birthDate)
        {
            Id = id;
            Name = name;
            Email = email;
            BirthDate = birthDate;
        }

        // Empty constructor for EF
        protected Customer() { }

        public string Name { get; private set; }

        public string Email { get; private set; }

        public DateTime BirthDate { get; private set; }
    }`

And my view model is

`    public class CustomerViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "The Name is Required")]
        [MinLength(2)]
        [MaxLength(100)]
        [DisplayName("Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The E-mail is Required")]
        [EmailAddress]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "The BirthDate is Required")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        [DisplayName("Birth Date")]
        public DateTime BirthDate { get; set; }
    }`

Everything is perfect map except Id (Guid)

Why cant map Guid? Is there any bug or Am i missing something?

Here is result:
Domain
![image](https://user-images.githubusercontent.com/2045788/57841766-d5c87600-77d3-11e9-949f-be3bea438267.png)

ViewModel
![image](https://user-images.githubusercontent.com/2045788/57841841-fd1f4300-77d3-11e9-8e32-4106fff79270.png)

**Comment by SteveWilkes** [comment]
Hi!

`CustomerViewModel.Id` isn't being mapped because [it's marked with the `[Key]` attribute](https://agilemapper.readthedocs.io/Entity-Mapping) - that often means mapping to a property which correlates with an auto-populated database primary key column, which throws exceptions with some versions of Entity Framework. 

There's a few work-arounds:

1. Remove the `[Key]` attribute
2. Enable key mapping globally using:

`Mapper.WhenMapping.MapEntityKeys();`

3. Enable key mapping for this mapping using:

```C#
Mapper.WhenMapping
    .From<Customer>().ToANew<CustomerViewModel>()
    .MapEntityKeys();
```

4. Add an `IEntity` interface with an `Id` member, and make an extension method to map it:

```C#
public static TDestination MapEntity<TSource, TEntity>(this TSource source)
    where TEntity : IEntity
{
    return Mapper.Map(source).ToANew<TEntity>(cfg => cfg.MapEntityKeys());
}
```

I've together [a fiddle](https://dotnetfiddle.net/A2ygZp) demonstrating some of the options :)

Cheers!

Steve

**Comment by muhammetsahin** [comment]
Awesome!

Thank you.

Can i use this also Project?

**Comment by SteveWilkes** [comment]
You're welcome!

The work-around for projection would be:

```C#
public static IQueryable<TEntity> ProjectEntity<TSource, TEntity>(
    this IQueryable<TSource> queryable)
    where TSource : IEntity
    where TEntity : IEntity
{
    return queryable.Project().To<TEntity>(cfg => 
        cfg.Map(s => s.Id).To(e => e.Id));
}
```

...but that's really an oversight on my part - projection will always be part of a 'read' mapping, so should always map entity keys. I'll fix that!

Cheers,

Steve

**Comment by muhammetsahin** [comment]
Thanks again.
