### ISSUE TITLE
Cannot configure handling of nulls in source

### ISSUE THREAD

**Issue by ste-b** [agileobjects/AgileMapper#145]
Hi,
I have a mapping between classes A and B, they both have other classes instances as properties; I cannot manage the case when those instances are null in the source, the mapper rather than putting the target to null also, it throws exception NullReferenceException

my case (simplified) is:

    class MsgSource
    {
        HdrSource hdr;
        DataSource data;
    }

    class DataSource
    {
        DataSourceContainer cont;
    }

    class DataSourceContainer
    {
        IdsSource ids;
        ResultSource res;
        OtherDataSource oth;
    }

    class MsgTarget
    {
        HdrTarget hdr;
        DataTarget data;
    }

    class DataTarget
    {
        IdsTarget ids;
        ResultTarget res;
        OtherDataTarget oth;
    }

through a mapper config class, I already map the container in the source which I don't have in the target

    WhenMapping
        .From<DataSource>().To<DataTarget>()
        .Map((srcData, tgtData) => srcData.cont).ToTarget()
        ;

I also define other explicit mappings related to inheritance, and for some data property with different names, otherwise they could not be managed automatically by the mapper.

I have the case that OtherDataSource instance in DataSourceContainer could be null, when the result is negative.
Even I added this mapping:

    WhenMapping
        .From<OtherDataSource>().ToANew<OtherDataTarget>()
        .If((srcData, tgtData) => srcData == null)
        .MapToNull()
        ;

still the mapping invocation throws the exception.
Having a look at the plan in cache, related to that property, I can see:

    dataTarget.oth =
    {
        try
        {
            var oth = dataTarget.oth ?? new OtherDataTarget();
            oth.COD = dataSource.cont.oth.COD;

            return (dataSource.cont.oth == null) ? null : oth;
        }
        catch (Exception ex)
        {
            throw MappingException.For(
                "CreateNew",
                "MsgSource.oth",
                "MsgTarget.oth",
                ex);
        }
    };

so I can explain the exception, because even though null is returned when dataSource.cont.oth is null, still the COD internal property is accessed without checking dataSource.cont.oth is null.
How can I configure the mapper such that this case is properly managed?
Thank you for your help.

**Comment by SteveWilkes** [comment]
Hi!

Thanks for the feedback - it doesn't look like this is anything you're doing wrong - the mapper has matched `DataSource.cont.oth.COD` to `DataTarget.oth.COD`, and is supposed to add appropriate null-checks.

Could you let me know the definitions of `OtherDataSource`, `OtherDataTarget` and the type of the `COD` properties?

Cheers,

Steve

**Comment by ste-b** [comment]
Hi,
thank you for the feedback!
I assumed it was a kind of mistake on my side, because i believed such a case would be common. In any case I put definition of the optional properties:

    class OtherDataSource
    {
        public string COD { get; set; }
    }

    class OtherDataTarget
    {
        public string COD { get; set; }
    }

Again this is simplified, but the concept is this: source and target are very similar, the problem is that in the source the data is optional, and when it is missing, it is null, not a created instance with eventually empty data fields.

thk,
Ste

**Comment by SteveWilkes** [comment]
This turned out to be a bug in adding null guards to the nested members of `.ToTarget()` sources - so `DataSource.cont` is guarded correctly, but `DataSource.cont.oth` isn't. It's fixed in the 1.5 release branch code - release to follow.

Thanks again!

Steve

**Comment by SteveWilkes** [comment]
This is fixed as of v1.5 preview 2, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper).

Thanks again for the feedback! :)

**Comment by ste-b** [comment]
Hi,
Now it's working, thank you very much for your help.
I'm happy I gave a small contribution to this project :)
Ste
