### ISSUE TITLE
was there any way to compare the object Values ?

### ISSUE THREAD

**Issue by sgf** [agileobjects/AgileMapper#151]
This may not be the goal of this project, but may be able to add this feature?

```C#
class TypeA{
Filed1;
Property2{get;set;}
}

Mapper.ValuesCompare<TypeA>(TypeA typea1,TypeA typea2);
//ValueCompare typea1's values is equal typea2's values
```

**Comment by SteveWilkes** [comment]
Hi,

That's a related feature, but it's not really what the project is intended to do, no. There are suggestions how to do that [here](https://stackoverflow.com/questions/4951233/compare-two-objects-and-find-the-differences)! :)

Thanks for the suggestion anyway!

Steve

**Comment by sgf** [comment]
I have been implement that by reflection and get member properties and their values, but performance no better.
where thank you,again @SteveWilkes
