### ISSUE TITLE
Load mapping configuration from data

### ISSUE THREAD

**Issue by mou7866** [agileobjects/AgileMapper#155]
Hi,

I have multiple mappings and I would like to map the relationships in a relational database. Is there an example where I can read the mappings for 2 objects and create the mappings at runtime based on the configuration in the database?

Thank you

Mohammed

**Comment by SteveWilkes** [comment]
Hi Mohammed,

The mapper doesn't support this out of the box, unfortunately - you'd have to write code to call configuration methods based on the data from the database.

All the best,

Steve
