### ISSUE TITLE
Triggering callbacks on projection call

### ISSUE THREAD

**Issue by brainboost** [agileobjects/AgileMapper#157]
Hello,
I tried to use anything from mapping callback described [here](https://agilemapper.readthedocs.io/configuration/Mapping-Callbacks/) and it seemed they didn't work with projections. They work for  mapping methods calls but not for `.ProjectUsing(_myMapper).To<MyModel>()`.  Is there any possibility to subscribe on something like **.After.CreatingInstances** or **.After.MappingEnds** to apply post-mapping value transformation? Thank you for any help!

**Comment by SteveWilkes** [comment]
Hi!

Unfortunately we can only include things in a projection which can be translated into SQL by the underlying `IQueryProvider`, so [callbacks and a few other things](https://agilemapper.readthedocs.io/query-projection/Configuration) aren't supported.

Cheers,

Steve
