### ISSUE TITLE
Support for IQueryable projection?

### ISSUE THREAD

**Issue by rgozim** [agileobjects/AgileMapper#18]
Hey, does AgileMapper have support for `IQueryable.Select` like AutoMapper's _Projections_ feature?

I really like the look of Agile Mapper and would like to apply it to EntityFrameworkcore queries!

**Comment by SteveWilkes** [comment]
Hi! It doesn't currently, although I do plan to add that feature. It won't be particularly soon though! Glad you like the look of the library :)

**Comment by SteveWilkes** [comment]
This is supported as of [v0.22](https://www.nuget.org/packages/AgileObjects.AgileMapper).
