### ISSUE TITLE
Is there a way to stop creation of a class when mapping properties?

### ISSUE THREAD

**Issue by AaronWells** [agileobjects/AgileMapper#19]
Given some classes that look like this:
```
class Source {
  public string MyCompositeA {get; set;}
  public string MyCompositeB {get; set;}
}
class Composite{
  public string A {get; set;}
  public string B {get; set;}
}
class Target {
  public Composite MyComposite{get; set;}
}
```
Is there a way to ensure that Target.MyComposite is not mapped if either Source.MyCompositeA or Source.MyCompositeB are null wherever the Composite class is used?

something like:
```
mapper.WhenMapping.ToANew<Composite>()
  .If((o, c) => string.IsNullOrWhiteSpace(c.A) || string.IsNullOrWhiteSpace(c.B))
  .Ignore();
```

**Comment by SteveWilkes** [comment]
Hi! Yep:

``` C#
mapper.WhenMapping
    .From<Source>()
    .ToANew<Target>()
    .If((s, t) => string.IsNullOrWhiteSpace(s.MyCompositeA) || string.IsNullOrWhiteSpace(s.MyCompositeB))
    .Ignore(t => t.MyComposite);
```

**Comment by SteveWilkes** [comment]
Oh! Sorry, I get what you're after now. There isn't currently a way to do that - I've considered putting in tracking of whether members of complex type properties actually get populated, and using that to skip mapping where appropriate, but there'd be a performance hit, so I'm not sure if I'll do it.

**Comment by SteveWilkes** [comment]
Ok! Sorry for the back-and-forth - I'm going to add this as a configurable option and push out a new release this weekend.

**Comment by SteveWilkes** [comment]
This is now fixed in v0.11. You can use:

```C#
mapper.WhenMapping
    .ToANew<Composite>()
    .If((o, c) => string.IsNullOrWhiteSpace(c.A) || string.IsNullOrWhiteSpace(c.B))
    .MapToNull();
```

Currently this will not apply in collections of `Composite` - you'll get unpopulated `Composite` instances instead of null entries in the result collection.

**Comment by AaronWells** [comment]
Thanks! You're the best.

**Comment by SteveWilkes** [comment]
Awww, shucks :)
