### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by polgarijog** [agileobjects/AgileMapper#2]
Hi,

just a quick question: is it .NET Core ready?

thanks - great work anyway

**Comment by SteveWilkes** [comment]
Not just yet, but support for .NETStandard1.0 is now on [my task list](https://github.com/agileobjects/AgileMapper/projects/1) for v1.0. I've spent today making my [ReadableExpressions](https://github.com/agileobjects/ReadableExpressions) library support .NETStandard1.0 - AgileMapper uses it to create mapping plans - so the mapper's next.

**Comment by polgarijog** [comment]
Thank you

**Comment by SteveWilkes** [comment]
I've just uploaded the [v0.4.0 NuGet package](https://www.nuget.org/packages/AgileObjects.AgileMapper/0.4.0) which targets .NETStandard1.0 as well as .NET4.0 :)
