### ISSUE TITLE
custom conversion of properties

### ISSUE THREAD

**Issue by avilv** [agileobjects/AgileMapper#208]
say i have a bunch of classes that have a specific convention for boolean->string
basically "Y/N" becomes true/false

```csharp
 public class PersonDTO 
 {
  [MapsToYN]
   public string Flag {get; set; }
 }

 public class PersonDB 
 {
  public bool Flag { get; set; }
 }

```
in essence i would like to identify properties with special attributes and override their default conversion behavior
i cant seem to find a way to do that, maybe i'm missing something

even a generic conversion for string -> bool 
.WhenMapping
                .From<bool>()
                .To<string>()
etc does not work, it seems to always use the default converter

**Comment by SteveWilkes** [comment]
Hi!

This should do the job:

```csharp
Mapper.WhenMapping
    .From<string>().To<bool>()
    .Map((s, b) => s == "Y").ToTarget();
```

I've put together [a .NET Fiddle](https://dotnetfiddle.net/xOnL45) showing it working.

Cheers!

Steve

**Comment by avilv** [comment]
hey steve, thanks - it seems i missed the "ToTarget" at the end

what about only performing this for properties which have some attribute? how would i go about that?

**Comment by SteveWilkes** [comment]
Hmmm - there isn't a way of doing that out of the box, unfortunately.

You could [do this](https://dotnetfiddle.net/7DWGp3), which would hopefully cover your scenarios?

```csharp
Mapper.WhenMapping
    .From<string>().To<bool>()
    .If((s, b) => s == "Y")
    .Map(true).ToTarget();
```

This only applies when the source string is `true`, otherwise it falls back to the default `string` -> `bool` conversion.

**Comment by avilv** [comment]
Hey, that's a shame - that workaround would work , but not when converting back from bool -> string, then i wouldn't have a way to know if the target property expects a "Y" or a "true" (or anything else for that matter)

**Comment by SteveWilkes** [comment]
That's a good point - I may look into extending `If` so it's possible to target members by criteria. Should hopefully be able to reuse the [member filtering API](https://agilemapper.readthedocs.io/configuration/Ignoring-Source-Members/#source-member-filtering), which includes attributes, member names, member types, etc.

**Comment by SteveWilkes** [comment]
This feature is supported as of v1.8, which is now available [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper).

The specific bool -> string configuration for string properties marked with a `YesOrNoAttribute` would be something like:

```csharp
Mapper.WhenMapping
    .From<bool>().To<string>()
   .IfTargetMemberMatches(m => m.HasAttribute<YesOrNoAttribute>())
    .Map((b, s) => b ? "Y" : "N").ToTarget();
```

Thanks for the feedback!

Steve
