### ISSUE TITLE
Unable to map class if property has JsonDocument class

### ISSUE THREAD

**Issue by NanFengCheong** [agileobjects/AgileMapper#210]
https://dotnetfiddle.net/vAa1An

**Comment by SteveWilkes** [comment]
Hi,

Might this be the same situation as issue #191 ?

Steve

**Comment by SteveWilkes** [comment]
Actually, sorry - I think it's just a configuration issue.

Instead of:
```csharp
Mapper.WhenMapping
    .From<JsonDocument>()
    .ToANew<JsonDocument>()
    .CreateInstancesUsing(ctx => JsonDocument.Parse(ctx.Source.RootElement.GetRawText(), default));
```

Use:
```csharp
Mapper.WhenMapping
    .From<JsonDocument>()
    .To<JsonDocument>()
    .CreateInstancesUsing(ctx => JsonDocument.Parse(ctx.Source.RootElement.GetRawText(), default));
```

Using `ToANew<T>()` applies the configuration only to new object mappings, not to updates as you're doing in your fiddle.

Hope that helps,

Steve

**Comment by NanFengCheong** [comment]
Seems working now. Thanks
