### ISSUE TITLE
file configuration

### ISSUE THREAD

**Issue by xbrossard** [agileobjects/AgileMapper#220]
I have to make an ORM-light on a specific database component access.
I have to map business objects to table like in Nhibernate, so i want to configure mapping using XML file generated by external tool (of modelisation)
actually, mapping configuration in AgileMapper can't be set dynamically using string configuration. I think it must be very interesting thing to do.
Perhaps, jus a documentation to know how to create dynamically expression gived to a mapper may be sufficient

thanks

**Comment by SteveWilkes** [comment]
Hi,

AgileMapper doesn't support configuration from XML. There's plenty of resources online explaining how to put together Expression Trees (for example https://expressiontree-tutorial.net).

All the best,

Steve
