### ISSUE TITLE
Correct usage of ThrowIfAnyMappingPlanIsIncomplete?

### ISSUE THREAD

**Issue by C-Wal** [agileobjects/AgileMapper#224]
If I use _mapper.WhenMapping.ThrowIfAnyMappingPlanIsIncomplete() then I get exceptions when my mapping runs but if I do not add _mapper.WhenMapping.ThrowIfAnyMappingPlanIsIncomplete() then the mapping works fine and returns my mapped object.  Is this expected? I'm using 1.8.1.

**Comment by SteveWilkes** [comment]
Hello!

[`ThrowIfAnyMappingPlanIsIncomplete`](https://agilemapper.readthedocs.io/Validating-Mappings) will throw an exception if the plan created for mapping two types:

- Will leave any target members unpopulated
- Not be able to construct or map to the members of any complex type members
- Not be able to map to particular target enum member values

A mapping plan is created either the first time any two types are mapped, or when you call one of the `Mapper.GetPlansFor<TSource>().To<TTarget>()` methods.

Hope that makes sense?

Steve

**Comment by C-Wal** [comment]
Yes thanks for that explanation.

FYI I do have a situation where the mapping works but adding [ThrowIfAnyMappingPlanIsIncomplete](https://agilemapper.readthedocs.io/Validating-Mappings) causes it to throws a 'Couldn't find a value for that key' exception but I don't have a repro yet.
