### ISSUE TITLE
override DateTime-to-String mapping?

### ISSUE THREAD

**Issue by brian-douglas** [agileobjects/AgileMapper#23]
I have many objects with complex object hierarchies to map.  My problem is with DateTime.ToString() -- which creates a string my clients are unable to use.  

I'm looking for a **generic** way to convert all DateTime's to custom strings, specifically using DateTime.ToString("o").    A nice solution might be to convert dates using CultureInfo  (Thread.CurrentThread.CurrentCulture.DateTimeFormat), but AgileMapper did not respond to CurrentCulture.

Any ideas?

**Comment by SteveWilkes** [comment]
The latest code uses CultureInfo.CurrentCulture.DateTimeFormat when mapping DateTimes to strings as you've suggested - release to follow. I also intend to add a more general-purpose solution.

Thanks for the feedback! :)

**Comment by SteveWilkes** [comment]
[Release 0.13](https://www.nuget.org/packages/AgileObjects.AgileMapper) contains the `CurrentCulture.DateTimeFormat` update; I've also added support for configuring mapper-wide [custom formatting strings](/agileobjects/AgileMapper/wiki/To-String-Formatting) for to-string mapping from a given type.

Apologies for the delay in the fix - I've been out of the country :)
