### ISSUE TITLE
Support mapping with tuple types

### ISSUE THREAD

**Issue by Luiz-Ossinho** [agileobjects/AgileMapper#233]
I believe this would be a great feature and would go along really well with the "zero configuration required" style of this package.

It would work as follows:

```csharp
//#r "nuget: AgileObjects.AgileMapper, 1.8.1"

using AgileObjects.AgileMapper;

public class TestClass
{
    public required int Id {get;set;}
    public required string Name {get;set;}
}

var testClassInstance = new TestClass
{ 
   Id = 1, 
   Name = "Name"
};

var mapped = Mapper.Map(testClassInstance).ToANew<(int Id, string Name)>();
Console.WriteLine(mapped);
// Output: (1, Name)
```

**Comment by SteveWilkes** [comment]
Hi,

Thanks for the suggestion! Unfortunately, tuple member names (in your example `Id` and `Name`) only exist at compile time - at runtime those members [are named](https://dotnetfiddle.net/C2afCs) `Item1` and `Item2`, so the mapper wouldn't be able to match them to anything.

All the best,

Steve
