### ISSUE TITLE
Can't convert StringValues to  a numeric types

### ISSUE THREAD

**Issue by maxlm** [agileobjects/AgileMapper#51]
AgileMapper version 0.20 

My target is: 
```
    class MyDTO 
    {
        public int intProp {get;set;}
        public string stringProp {get;set;}
        public string[] stringArrProp {get;set;}
        public double doubleProp {get;set;}
        public int[] intArrProp {get;set;}
        public double[] doubleArrProp {get;set;}
    }
```

Source is: 
```
 var sourceDict = new Dictionary<string, StringValues>{
                ["intProp"] = new StringValues("32424"),
                ["stringProp"] = new StringValues("not so long string prop value"),
                ["stringArrProp"] = new StringValues(new string[]{"string1", "string2"}),
                ["doubleProp"] = new StringValues("35.4354"),
                ["intArrProp"] = new StringValues(new string[]{"1", "2", "3", "4", "5", "6"}),
                ["doubleArrProp"] = new StringValues(new string[]{"1.23", "2.23", "3.23", "4.23"})
            };
```

and code is 
```
var result =  Mapper.Map(sourceDict).ToANew<MyDTO>();
```

`intProp` and `doubleProp` values are not mapped. 
Here is  result: 

<img width="446" alt="screenshot 2018-02-02 21 41 35" src="https://user-images.githubusercontent.com/1958711/35753024-c710f002-0866-11e8-81b6-90abd2bef4bd.png">

```
Mapper.GetPlansInCache()
```
shows
```
 // No data source for intProp
 // No data source for doubleProp
```
for not mapped fields. Works the same way for decimal too.

**Comment by SteveWilkes** [comment]
Hello again! This is fixed in the latest code - I'll push out a patch release in the next few days.

Thanks again for the feedback :)

**Comment by SteveWilkes** [comment]
This is fixed in [v0.21](https://www.nuget.org/packages/AgileObjects.AgileMapper).

The mapper now uses implicit or explicit to-String operators for string conversions where available.

**Comment by maxlm** [comment]
Hi, 

that doesn't work for me. Same steps and same result as given in issue description

**Comment by SteveWilkes** [comment]
Hmm, that's odd - I've made .NET Fiddle [here](https://dotnetfiddle.net/ma3uIW), and it's working. Could you double-check you're using v0.21?

**Comment by maxlm** [comment]
yes, I'm using v0.21
here is my `.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AgileObjects.AgileMapper" Version="0.21.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.0.0" />
  </ItemGroup>
  
</Project>
```

but maybe the difference is in environment.  
.NET Fiddle can't run that example on  Roslyn. 
Here my environment info:  
``` 
.NET Command Line Tools (2.1.4)
Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by SteveWilkes** [comment]
Ahh, ok - I'll look at it again and get back to you tomorrow.

**Comment by SteveWilkes** [comment]
Just to say I've reproduced this with .NET Core 2. I'll have a fix in the next few days.

**Comment by SteveWilkes** [comment]
Hi,

I've just added [v0.21.1](https://www.nuget.org/packages/AgileObjects.AgileMapper/0.21.1), which contains a few different fixes for NetCoreApp2 projects. Please give it a try and let me know how it is!

Thanks :)

**Comment by maxlm** [comment]
yes, that works. Thanks!

**Comment by SteveWilkes** [comment]
Great stuff - you're welcome! Thanks for the feedback and your patience :)
