### ISSUE TITLE
Can you add support for .net35?

### ISSUE THREAD

**Issue by YandyZaldivar** [agileobjects/AgileMapper#66]
I need to target:

net35
net40
net45
netstandard1.3
netstandard2.0

It is ok for me if the workaround used for supporting net35 affects performance on that target.

**Comment by SteveWilkes** [comment]
Hi!

I'll add a net35 target and see what the results are. I'll get back to you! :)

**Comment by YandyZaldivar** [comment]
Excellent, I was using Automapper, but with last release I don't see support for .net40 and now I end up targeting 3 different versions with workarounds and conditional compilation:

net35 `<PackageReference Include="AutoMapper" Version="1.1.0.118" />`
net40 `<PackageReference Include="AutoMapper" Version="6.2.2" />`
rest + `<PackageReference Include="AutoMapper" Version="7.0.1" />`

My use cases are relatively simple, I need to map Dictionary<string, object> to my models, and models to models ignoring all unmapped properties on both target and source, or alternatively placing a IgnoreAttribute on desired properties. Other use cases should appear with time.

For the case of the dictionary this is the code I am using, basically I am mapping from a html query string to a model, I haven't use AgileMapper but reading in the documentation it should work. Here is my working code with automapper:

```
var dictionary = new Dictionary<string, object>();
var pairs = argument.Split('&');

foreach (var pair in pairs)
{
    var tuple = pair.Split('=');
    if (!dictionary.ContainsKey(tuple[0]))
        dictionary.Add(tuple[0], string.IsNullOrEmpty(tuple[1]) ? null : tuple[1]);
}

model = node.Mapper.Map(dictionary, dictionary.GetType(), command.RequestModel.GetType());
```

**Comment by SteveWilkes** [comment]
Ouch! Yeah, that doesn't sound like a fun way of doing it.

AgileMapper doesn't currently support mapping to target types not known at design time, but it'd be a 
straightforward addition. That would make the equivalent code:

```C#
model = node.Mapper.Map(dictionary).ToANew(command.RequestModel.GetType());
```

**Comment by YandyZaldivar** [comment]
Yes, sometimes the type of the models are obtained through reflection, so I need to be able to pass the type info instead of a generic class `<T>`.

**Comment by SteveWilkes** [comment]
Just to note this is looking possible - I've added your NET35 pull request to NetStandardPolyfills (thanks!) and am currently updating [ReadableExpressions](https://github.com/agileobjects/ReadableExpressions). The NET35 version has to use the [DynamicLanguageRuntime](https://www.nuget.org/packages/DynamicLanguageRuntime) to generate and compile its Expressions, but looks like it should work :)

**Comment by SteveWilkes** [comment]
Support for .NET 3.5 added in [v0.25](https://www.nuget.org/packages/AgileObjects.AgileMapper) - please let me know how you get on!

**Comment by YandyZaldivar** [comment]
Excellent, when I update my projects I will let you know.

**Comment by YandyZaldivar** [comment]
I started using AgileMapper today, everything working fine!

Quick question:
`var queryString = AgileObjects.AgileMapper.Mapper.Flatten(new MyModel()).ToQueryString();`

Is there a built-in way to achieve the opposite?
`var myObject = ...FromQueryString(queryString);`
