### ISSUE TITLE
Does UseConfiguration order change the execution plan ?

### ISSUE THREAD

**Issue by gbansk** [agileobjects/AgileMapper#74]
If i create two classes, parent and child and a mapping configuration for both, i have noticed that of resulting plans differ depending on the order of the `UseConfiguration` call.

            mapper = Mapper.CreateNew();
            mapper.WhenMapping.UseConfigurations
                .From<ParentMappingConfiguration>(myValue)
                .From<ChildMappingConfiguration>(myValue);

The resulting plan produces

```
mapper.GetPlansFor<Parent>().To<ParentDto>()
{// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// Map Parent -> ParentDto
// Rule Set: CreateNew
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

pToPdData =>
{
    try
    {
        var parentDto = new ParentDto();
        // No data source for MyChild or any of its child members

        return parentDto;
    }
    catch (Exception ex)
    {
        throw MappingException.For(
            "CreateNew",
            "Parent",
            "ParentDto",
            ex);
    }
}

```
and the child configuration is missing.

However, if i change the call to 

            mapper = Mapper.CreateNew();
            mapper.WhenMapping.UseConfigurations
                .From<ChildMappingConfiguration>(myValue)
                .From<ParentMappingConfiguration>(myValue);

The resulting plan is 
```
GetPlansFor<Parent>().To<ParentDto>()
{// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// Map Parent -> ParentDto
// Rule Set: CreateNew
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

pToPdData =>
{
    try
    {
        var parentDto = new ParentDto();

        if (pToPdData.Source.MyChild != null)
        {
            parentDto.MyChild =
            {
                try
                {
                    var childDto = parentDto.MyChild ?? new ChildDto();
                    childDto.IsMyCountGtrZero = pToPdData.Source.MyChild.IsMyCountGtrZero(vals);

                    return childDto;
                }
                catch (Exception ex)
                {
                    throw MappingException.For(
                        "CreateNew",
                        "Parent.MyChild",
                        "ParentDto.MyChild",
                        ex);
                }
            };
        }

        return parentDto;
    }
    catch (Exception ex)
    {
        throw MappingException.For(
            "CreateNew",
            "Parent",
            "ParentDto",
            ex);
    }
}
```
which include the child mapping and it works as expected.

Is there an order requirement for `useConfiguration`, or an i missing something?

From looking at the documentation here: [https://github.com/agileobjects/AgileMapper/wiki/Configuration-Classes](https://github.com/agileobjects/AgileMapper/wiki/Configuration-Classes) I could not find any details about dependency ordering?

Thanks,
Gary.

**Comment by SteveWilkes** [comment]
Hi Gary,

There certainly shouldn't be an ordering requirement - could you post the contents of your configuration classes so I can reproduce the issue?

Thanks,
Steve

**Comment by gbansk** [comment]
Hi Steve,

ParentMapper.cs (Config)

```using System;
using System.Collections.Generic;
using System.Text;
using AgileObjects.AgileMapper;
using AgileObjects.AgileMapper.Configuration;

namespace AgileMapperUseConfigurationTest
{
    public class ParentMappingConfiguration : MapperConfiguration
    {
        protected override void Configure()
        {
            WhenMapping
                .From<Parent>()
                .To<ParentDto>();

            GetPlansFor<Parent>().To<ParentDto>();
        }
    }

    public class ParentMapper : IDtoMapper<Parent, ParentDto>
    {
        private readonly IMapper _mapper;

        public ParentMapper(List<int> myValue)
        {
            _mapper = Mapper.CreateNew();
            _mapper.WhenMapping.UseConfigurations
                .From<ParentMappingConfiguration>(myValue)
                .From<ChildMappingConfiguration>(myValue)
        }

        public ParentDto Map(Parent parent)
        {
            return _mapper.Map(parent).ToANew<ParentDto>();
        }
    }
}
```

and ChildMapper

```using System;
using System.Collections.Generic;
using System.Text;
using AgileObjects.AgileMapper;
using AgileObjects.AgileMapper.Configuration;

namespace AgileMapperUseConfigurationTest
{
    public class ChildMappingConfiguration : MapperConfiguration
    {
        protected override void Configure()
        {
            var vals = GetServiceOrThrow<List<int>>();
            WhenMapping
                .From<Child>()
                .To<ChildDto>()
             .And
             .Map(ctx => ctx.Source.IsMyCountGtrZero(vals)).To(o => o.IsMyCountGtrZero);

            GetPlansFor<Child>().To<ChildDto>();
        }
    }

        public class ChildMapper : IDtoMapper<Child, ChildDto>
        {
            private readonly IMapper _mapper;

            public ChildMapper(List<int> myValue)
            {
                _mapper = Mapper.CreateNew();
                _mapper.WhenMapping.UseConfigurations
                    .From<ChildMappingConfiguration>(myValue)
            }

            public ChildDto Map(Child child)
            {
                return _mapper.Map(child).ToANew<ChildDto>();
            }
        }
    }
```

Cheers,
Gary.

**Comment by gbansk** [comment]
Sorry, pressed the wrong button!

**Comment by SteveWilkes** [comment]
Thanks very much - I'll check this out and get back to you :)

**Comment by SteveWilkes** [comment]
Hi Gary,

Looking at this, I probably should have realised what the issue was sooner - sorry about that.

When you call `GetPlansFor<Parent>().To<ParentDto>();`, the mapper creates and caches the set of mapping plans for `Parent` -> `ParentDto` using the information it has at that time. Without the `Child.IsMyCountGtrZero(vals)` -> `ChildDto.IsMyCountGtrZero` mapping configured, I'm guessing it doesn't know how to map *any* of `ChildDto`s members, so instead of creating an empty `ChildDto` object, it leaves that property as [null](/agileobjects/AgileMapper/wiki/Null-Results).

When `ChildMappingConfiguration` is executed first, `GetPlansFor<Parent>().To<ParentDto>();` knows how to map `Child.IsMyCountGtrZero(vals)` -> `ChildDto.IsMyCountGtrZero`, so it goes ahead and includes the `ChildDto` mapping in the plan.

Based on this, I'll add support for ordering `MapperConfigurations` when they're applied automatically -through `UseConfigurations.FromAssemblyOf<ParentDto>`, for example.

Incidentally, the way your configurations get the `List<int>` will change in the next release. Instead of:

```C#
var vals = GetServiceOrThrow<List<int>>();

WhenMapping
    .From<Child>().To<ChildDto>()
    .Map(ctx => ctx.Source.IsMyCountGtrZero(vals))
    .To(o => o.IsMyCountGtrZero);
```

...it'll be:

```C#
WhenMapping
    .From<Child>().To<ChildDto>()
    .Map(ctx => ctx.Source.IsMyCountGtrZero(ctx.GetService<List<int>>()))
    .To(o => o.IsMyCountGtrZero);
```

The `List<int>` returned will be supplied via a service provider you register with the mapper, which will make sure the appropriate value is returned for the context. I'll update the documentation once the release it out.

**Comment by SteveWilkes** [comment]
Configuration ordering now documented [in the wiki](/agileobjects/AgileMapper/wiki/Configuration-Classes#ordering-configurations).
