### ISSUE TITLE
 [question] is it possible to map collections to a new type of collection inline?

### ISSUE THREAD

**Issue by jackweldon** [agileobjects/AgileMapper#83]
Hey ,  

I've been using agile mapper on a side project and was wondering if there was a way of mapping so that you can create new object instances on the target from a member of the source.
```

    public class ParentModel
    {
        public int Id { get; set; }
 
        public ParentModel()
        {
            ChildNames = new Collection<string>();
        }
        public ICollection<string> ChildNames { get; set; }
    } 

    public class Parent 
    {        
        public ICollection<Child> Children { get; set; } 

        public Tournament () {
            Children = new Collection<Child> ();
        }
    }
```

    Parent result = _mapper.Map(parentModel).ToANew<Parent>();

So in the above case the result variable would have a list of Child object with the name property of each being set to the string value of the ChildNames.

Rather than something like

       foreach(var name in parentModel.ChildNames)
        {
           result.Children.Add(new Chlid() { Name = name });
        }

Does this make sense?

Think the library is great by the way!

**Comment by SteveWilkes** [comment]
Hey Jack, good to hear from you!

You can do it like this:

```C#
var parent = Mapper.Map(parentModel).ToANew<Parent>(cfg => cfg
    .Map((pm, p) => pm.ChildNames.Select(cn => new Child { Name = cn }))
    .To(p => p.Children));
```

...I've put together [a fiddle](https://dotnetfiddle.net/VlijtK) showing it. It's kind of doing the mapping yourself at this stage, so I might add this sort of thing in as a [meta member](/agileobjects/AgileMapper/wiki/Meta-Members), although the naming in this exact case would make it awkward.

Hope that helps, glad you're finding the mapper useful!

All the best,

Steve

**Comment by SteveWilkes** [comment]
...actually, there's another way of doing it :) I've made [another fiddle](https://dotnetfiddle.net/0FL4L8):

```C#
var parent = Mapper.Map(parentModel).ToANew<Parent>(
    cfg => cfg.Map((pm, p) => pm.ChildNames).To(p => p.Children),
    cfg => cfg.WhenMapping.From<string>().To<Child>().Map(ctx => ctx.Source).To(c => c.Name));
```

...ORRRRRRRRR you could add a constructor to `Child` and configure it like this:

```C#
var parent = Mapper.Map(parentModel).ToANew<Parent>(
    cfg => cfg.Map((pm, p) => pm.ChildNames).To(p => p.Children),
    cfg => cfg.WhenMapping.From<string>().To<Child>().Map(ctx => ctx.Source).ToCtor<string>());
```
