### ISSUE TITLE
Auto-apply MapperConfigurations specified using ApplyAfter attributes

### ISSUE THREAD

**Issue by gbansk** [agileobjects/AgileMapper#91]
1) I have a class that inherits a few properties and I have noticed that by default, i have to create a map for each of these properties, they are not automatically mapped, is this the expected behaviour?

2) If I have the following configurations, Grandparent, Parent, Child, and grandparent maps the parent configuration, parent maps the child configurationand I have used the ApplyAfter to make sure that child is mapped before parent, and parent is mapped by grandparent I get an MappingConfigurationException error if the grandparent does not also include the child configuration.

Is it possible to define the mappings at the lower levels and not additionally reference the configurations at a higher level.  That is, if parent maps child, then grandparent only needs to reference parent configuration and not additionally the child configuration.

I suspect that this is caused the the ApplyAfter attribute.

Hope this maps sense,

Thanks,
Gary

**Comment by SteveWilkes** [comment]
Hey Gary,

Inherited properties should definitely be mapped by default - I've put together [a fiddle](https://dotnetfiddle.net/CsM0Or) and it looks to be working. Could you paste the models into here?

This setup:

```C#
[ApplyAfter(typeof(ParentConfiguration))]
GrandparentConfiguration : MapperConfiguration
{
}

[ApplyAfter(typeof(ChildConfiguration))]
ParentConfiguration : MapperConfiguration
{
}

ChildConfiguration : MapperConfiguration
{
}
```

...should definitely work - could you confirm that's how you've got it?

Cheers,

Steve

**Comment by gbansk** [comment]
Hay Steve,

Thanks for the response, After playing around with the fiddle you setup, I tested a couple different scenarios and they all worked, so now its just going back and looking at our implementation.

In reference to the grandparent, parent, child question, I didn't really explain the question very well and it might be our implementation.  I will attempt to explain it again.

if you refer to the code segment i provided in [Issue 74 - ParentMapper.cs](https://github.com/agileobjects/AgileMapper/issues/74)

It was not the configuration i meant, it was the using configuration 

Child
```
            _mapper.WhenMapping.UseConfigurations
                .From<ChildMappingConfiguration>(myValue)
```
Parent
```
            _mapper.WhenMapping.UseConfigurations
                .From<ChildMappingConfiguration>(myValue)
                .From<ParentMappingConfiguration>(myValue)
```
GrandParent
```
            _mapper.WhenMapping.UseConfigurations
                .From<ChildMappingConfiguration>(myValue)
                .From<ParentMappingConfiguration>(myValue)
                .From<GrandParentMappingConfiguration>(myValue)
```

Each parent needs to list all configurations for their children, is it possible to allow the parent to internally reference the child so that the configs would look something like, given that ApplyAfter has been used and therefore you know dependencies?

Child
```
            _mapper.WhenMapping.UseConfigurations
                .From<ChildMappingConfiguration>(myValue)
```
Parent
```
            _mapper.WhenMapping.UseConfigurations
                .From<ParentMappingConfiguration>(myValue)
```
GrandParent
```
            _mapper.WhenMapping.UseConfigurations
                .From<GrandParentMappingConfiguration>(myValue)
```

Thanks for your time,

Gary.

**Comment by SteveWilkes** [comment]
Ahhhhhhh- I understand now. So `UseConfigurations.From<T>` would follow any `ApplyAfter` attributes and apply the configurations they specify automatically? Yeah, that sounds completely sensible. I'll make it so :)

...if that wasn't what you meant, please do say so :)

**Comment by SteveWilkes** [comment]
The latest code now follows chains of `ApplyAfter` attributes and applies the configurations in order, from a root configuration type you specify. Release to follow.

Thanks for the feedback! :)

**Comment by SteveWilkes** [comment]
Configurations specified in `ApplyAfter` attributes are automatically applied in the right order as of [v0.27]((https://www.nuget.org/packages/AgileObjects.AgileMapper)).

Cheers again, Gary! :)

**Comment by gbansk** [comment]
Hi Steve, 

Thanks for the updated version.

While implementing the changes I have a configuration 'ApplyAfter' infinite loop.  One of the child MapperConfigurations referenced a parent configuration.

Might be worth putting a check in so people like me don't get it wrong. 

Thanks again,

Gary.

**Comment by SteveWilkes** [comment]
Hey Gary!

The mapper does actually check for infinite loops - there's a test [ShouldErrorIfMapperConfigurationsHaveACircularDependency](https://github.com/agileobjects/AgileMapper/blob/master/AgileMapper.UnitTests.NonParallel/Configuration/WhenApplyingMapperConfigurationsIncorrectly.cs).

Was it GrandParent -> Parent -> Child -> GrandParent? Or something more elaborate?

Cheers,

Steve

**Comment by gbansk** [comment]
Hi Steve,

Here are the relationships and scenario.

Customer can have notes
Order can have notes
Mapping can be done against either Customer or Order

Customer -> notes
Customer -> Orders -> notes

So the ApplyAfter attribute is applied against the Orders and not against Customer (since customer has to have Orders) and the ApplyAfter attribute is applied against Customer for Orders

So what I had incorrect was an ApplyAfter on Notes against Customer.

This was causing the loop issue for me.

Hope the explanation of the relationships make sense and it helps.

The ApplyAfter attribute has cleaned up the code quite nicely, thank you for that.

Cheers,
Gary.

**Comment by SteveWilkes** [comment]
Thanks Gary - I'll check it out - glad it's useful! :)
