### ISSUE TITLE
Exception thrown Mapping readonly dictionary member

### ISSUE THREAD

**Issue by krema** [agileobjects/AgileMapper#97]
Hi, 
I am trying to map an user entity with its property to a list of claims. The following example throws an exception and I haven't found a solution to this issue yet. It would be nice if someone could clarify whether it is a bug or a mistake of mine. Thanks

    Mapper.WhenMapping.From<Entities.User>()
              .ToANew<List<Claim>>()
              .Map((s, d) => CreateClaims(s))
              .ToTarget()

    Mapper.WhenMapping.From<Entities.User>()
              .ToANew<UserDTO>()
              .Map((user, dto) => config.Map(user).ToANew<List<Claim>>())
              .To(dto => dto.Claims)

    private IList<Claim> CreateClaims(Entities.User user)
    {
      return new List<Claim>
      {
          new Claim("firstName", user.FirstName),
          new Claim("lastName", user.LastName),
          new Claim("defaultLanguage", user.DefaultLanguage),
          new Claim("disabled", Convert.ToInt32(user.Disabled).ToString(), ClaimValueTypes.Boolean),
          new Claim("isInternalUser", Convert.ToInt32(user.Internal).ToString(), ClaimValueTypes.Boolean),
          new Claim("userId", user.Id.ToString(), ClaimValueTypes.Integer32)
      };
    }

The exception very shortened

```
System.ArgumentException : Expression must be writeable
Parameter name: left
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at System.Linq.Expressions.BinaryExpression.Update(Expression left, LambdaExpression conversion, Expression right)
   at AgileObjects.AgileMapper.Extensions.Internal.ExpressionExtensions.ExpressionReplacer.ReplaceIn[TExpression](TExpression expression, Func`2 replacer)
   at AgileObjects.AgileMapper.Extensions.Internal.ExpressionExtensions.ExpressionReplacer.ReplaceIn[TExpression](TExpression expression, Func`2 replacer)
   at AgileObjects.AgileMapper.Extensions.PublicEnumerableExtensions.Project[TItem,TResult](IEnumerable`1 items, Func`2 projector)+MoveNext()
```

**Comment by SteveWilkes** [comment]
Hi!

If I've understood correctly, I think this should work:

```C#
Mapper.WhenMapping
    .From<Entities.User>().To<UserDto>()
    .Map(ctx => CreateClaims(ctx.Source))
    .To(dto => dto.Claims);

// And then:
var dto = Mapper.Map(user).ToANew<UserDto>();
```

I've put together [a .NET Fiddle](https://dotnetfiddle.net/CEYohP) showing it in action. Hope that helps?

**Comment by krema** [comment]
Hi Steve,
Thank you for your reply. You helped me to find the cause why I got an exception. If I use the Claim class from System.Security.Claims you will get this error.

    System.ArgumentException : Expression must be writeable

I forked your [.NET fiddle](https://dotnetfiddle.net/wqHEuF) example and used the Claim class from Microsoft. Is that a bug in AgileMapper?

Thanks

**Comment by SteveWilkes** [comment]
Hey!

There is a bug here, yeah - but the configuration I suggested doesn't actually quite do what you wanted, either. It's setting up `CreateClaims(user)` as the source of a mapping from the `CreateClaims()` result to the target `Claims` collection. That's not what we want - we just want the `CreateClaims()` result mapped directly onto the `UserDto.Claims` property.

We should therefore use this instead:

```C#
Mapper.WhenMapping
    .From<Entities.User>().To<UserDto>()
    .After.MappingEnds
    .Call(ctx => ctx.Target.Claims = CreateClaims(ctx.Source));
```

I've [forked your fork](https://dotnetfiddle.net/whuR4r), and it's working.

The bug is occurring as the mapper tries to figure out how to clone a `Claim` - I'll get that fixed.

Cheers,

Steve

**Comment by SteveWilkes** [comment]
This turned out to be a bug where mapping from an `IDictionary<,>` member to a readonly `IDictionary<,>` member (in this case `Claim.Properties` -> `Claim.Properties`) was trying to populate the readonly member.

Fixed in the latest code, release to follow.

Thanks for the feedback! :)
